#!/usr/bin/env bash

jobEnvFile=$1
additionalEnv=""
if [[ "${2^^}" == "DRYRUN" ]]; then
    export REPO_CRAWLER_DRY_RUN=true
fi

configDir=$(dirname "$jobEnvFile")
fileName=$(basename "$jobEnvFile")
binaryName="$configDir/crawler"
if [[ "$fileName" == "db."* ]]; then
    #DB file is sent, requires Repo file as well
    repoName=$(echo "$fileName" | cut -d. -f 2- | rev | cut -d. -f 3- | rev)
    repoFile="$configDir/repo.${repoName}.env"
    export $(grep -v '^#' "$repoFile" | xargs)
else
    export REPO_CRAWLER_ACCOUNT_DISCOVERY=true
    export REPO_CRAWLER_DATA_CLASSIFICATION=false
    export REPO_CRAWLER_REPO_DATABASE=none
fi

cpEnvFile="$configDir/controlplane.env"

if [ ! -r "$jobEnvFile" ]; then
    echo "Unable to find job file: '$jobEnvFile'"
    exit 1
elif [[ -n "$repoFile" && ! -r "$repoFile" ]]; then
    echo "unable to access  repo file for data discovery: '$repoFile'"
elif [ -z "$cpEnvFile" ]; then
    echo "Unable to find Control Plan config file: '$cpEnvFile'"
    exit 1
fi

export $(grep -v '^#' "$jobEnvFile" | xargs)
export $(grep -v '^#' "$cpEnvFile" | xargs)

if [ ! -x "$binaryName" ]; then
    image="us-docker.pkg.dev/cyralinc/cyral-repo-crawler/cyral-repo-crawler:v0.5.3"
    
    dockercmd="docker run --rm --name crawler -d --entrypoint /bin/sleep $image 10"
    dockercp="docker cp crawler:/bin/crawler $binaryName"
    
    if ! sudoOutput=$(eval sudo -n "$dockercmd" 2>&1); then
        if ! stdOutput=$(eval "$dockercmd" 2>&1); then
            echo "FAILED to invoke crawler job!"
            echo "Sudo Attempt: $sudoOutput"
            echo "Standard Attempt: $stdOutput"
        else
            output="$stdOutput"
            eval "$dockercp"
        fi
    else
    output="$sudoOutput"
    eval sudo -n "$dockercp"
    fi
fi
echo "$output"
$binaryName